import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius } from '../theme/colors';

/** Shared look for the read-and-sign documents. */
export const docStyles = StyleSheet.create({
  scroll: { padding: spacing.lg, paddingBottom: 48 },
  step: {
    color: colors.brand.orange,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: spacing.sm,
  },
  section: { marginBottom: spacing.md },
  heading: { color: colors.text.primary, fontSize: 13, fontWeight: '800', marginBottom: 6 },
  para: { color: colors.text.secondary, fontSize: 12, lineHeight: 18, marginBottom: 6 },
  list: { paddingLeft: 4 },
  end: { color: colors.text.muted, fontSize: 10, textAlign: 'center', marginVertical: spacing.md },
  unlocked: { color: colors.status.success, fontSize: 11, textAlign: 'center', marginBottom: spacing.md },
  jump: {
    borderWidth: 1,
    borderColor: colors.border.orange,
    borderRadius: borderRadius.md,
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  jumpText: { color: colors.brand.orange, fontSize: 11, fontWeight: '700' },
  signBox: {
    borderWidth: 1,
    borderColor: colors.border.primary,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    backgroundColor: colors.bg.card,
  },
  label: {
    color: colors.text.secondary,
    fontSize: 11,
    fontWeight: '700',
    marginTop: spacing.sm,
    marginBottom: 4,
  },
  input: {
    backgroundColor: colors.bg.input,
    borderWidth: 1,
    borderColor: colors.border.primary,
    borderRadius: borderRadius.sm,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text.primary,
    fontSize: 14,
  },
  inputError: { borderColor: 'rgba(239,68,68,0.7)' },
  fieldError: { color: '#f87171', fontSize: 10, marginTop: 2 },
  readonly: { color: colors.text.muted, fontSize: 12, marginTop: 2 },
  ackRow: { flexDirection: 'row', gap: 8, marginTop: spacing.md, alignItems: 'flex-start' },
  ackBox: { color: colors.brand.orange, fontSize: 18, lineHeight: 20 },
  ackText: { flex: 1, color: colors.text.secondary, fontSize: 11, lineHeight: 16 },
  error: {
    color: '#f87171',
    fontSize: 11,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.3)',
    borderRadius: borderRadius.sm,
    padding: 8,
    marginTop: spacing.sm,
  },
  submit: {
    backgroundColor: '#059669',
    borderRadius: borderRadius.md,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: spacing.md,
  },
  submitText: { color: '#fff', fontWeight: '800', fontSize: 13 },
});
